# 資料庫連線網址
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_system_db

# 資料庫登入帳號 (使用你的電腦使用者名稱)
spring.datasource.username=chenzhengying

# 資料庫登入密碼 (明文測試確保穩定)
spring.datasource.password=YOURS_PASSWORD

# PostgreSQL 的驅動程式
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate 設定
# update：自動幫你同步 Java Entity 到資料庫表格
spring.jpa.hibernate.ddl-auto=update
# show-sql：顯示執行中的 SQL 語句
spring.jpa.show-sql=true

# 強制指定資料庫語法版本，解決 Unable to determine Dialect 錯誤
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect